image: docker:stable
# services:
#   - docker:dind
# variables:
#   # When using dind service we need to instruct docker, to talk with the
#   # daemon started inside of the service. The daemon is available with
#   # a network connection instead of the default /var/run/docker.sock socket.
#   #
#   # The 'docker' hostname is the alias of the service container as described at
#   # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services

#   # tcp://localhost:2375 because of how Kubernetes executor connects services
#   # to the job container
#   DOCKER_HOST: tcp://docker:2375/
#   # When using dind, it's wise to use the overlayfs driver for
#   # improved performance.
#   DOCKER_DRIVER: overlay2
stages:
  - build

before_script:
  - echo `pwd` # debug
  - docker login -u b2pUi -p $ecrToken b2pui.azurecr.io
  - echo b2pui.azurecr.io/mfec/ui:$CI_COMMIT_TAG

Build:
  stage: build
  script:
    - echo $CI_COMMIT_TAG > ./src/version.txt
    - docker build -t b2pui.azurecr.io/mfec/ui:$CI_COMMIT_TAG .
    - docker push b2pui.azurecr.io/mfec/ui:$CI_COMMIT_TAG
  only:
    - tags
