version: '3.1'

services:
  node:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - NODE_ENV=production

    command: npm run start

    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
      - ./.env:/opt/app/.env
    environment:
      - NODE_ENV=production
